### PR TITLE
Layout

### PR DESCRIPTION
**Pull request by OneOneFour**

### CODE REVIEW

**Comment by FreyaXH** [comment]
Hi Rob, I'm not sure why the top right hotspot toggle doesn't align properly on my laptop. Could you please check if this only happens on my side? Thanks : )
6c761b7b2016b6e72cbe2d7589cffc56

**Comment by OneOneFour** [comment]
> Hi Rob, I'm not sure why the top right hotspot toggle doesn't align properly on my laptop. Could you please check if this only happens on my side? Thanks : )
> 6c761b7b2016b6e72cbe2d7589cffc56
Yeah I can tell for a first that you have left the default #app styling from the Vue CLI template, so you will need to remove that for sure (why the top edge is offset). I am not sure if the fix that me and @dtorrenp came up with yesterday has made it in to this PR?

**Comment by OneOneFour** [comment]
Try this commit @FreyaXH

**Comment by OneOneFour** [comment]
(ofc you will need to rollup build after fetching this PR)

**Pull request merged**
