### PR TITLE
Hover Text component

### PR DESCRIPTION
**Pull request by darrenlean**
1. Created hover text component: When the cursor is in the region of text, the cursor changes into a 'help' cursor (does not appear on screenshot below) and an additional text appears
2. Corrected a typo in an event emitted by Dropdown Text Box component

HoverTextInitial
HoverTextFinal

### CODE REVIEW

**Comment by OneOneFour** [comment]
Hi Darren, summary of the comments from earlier.
I think it would be better to remove your dropdownText prop and replace with a named slot, because then the user can input whatever html they like in the the dropdown (or even markdown 👀 👀 )
Also would be nice to add a prop to control the delay between when the user mouse goes off the text to when the hover text begins to fade out.
Finally, worth checking if any mobile touch API events are worth listening to and geting some feedback from the rest of @Imperial-visualizations/core to ensure that they like the interaction on a mobile device?

**Comment by darrenlean** [comment]
Update:
1. Slots (named and unnamed) have been used where suitable
2. HoverText content follows cursor (see attached screenshots) - I would like anyone has the time to play with it to see if it truly follows your cursor without offset
3. All components that I have created, except HoverText, work well on my phone through local playground server

Screenshot 2020-07-01 at 10 45 49 am
Screenshot 2020-07-01 at 10 45 52 am

**Comment by darrenlean** [comment]
> Looks good although I would remove the hoverreposition event since I don't think this would ever be useful.

Thanks for the feedback, Rob! I agree with you and have therefore removed the hoverrepostion event emitter.

**Comment by darrenlean** [comment]
> Great work Darren!
> There is only one small problem. When my cusor hovering on the hover element, a small question mark always appears next to it. Did you deliberately make this feature or it is some default settings?

Hey Freya,

Yes, the 'help' cursor is done on purpose since the component is meant to be explaining the main text. I thought that changing the cursor will make it more obvious that the extra text is an optional text.

**Comment by FreyaXH** [comment]
> > Great work Darren!
> > There is only one small problem. When my cusor hovering on the hover element, a small question mark always appears next to it. Did you deliberately make this feature or it is some default settings?
> 
> Hey Freya,
> 
> Yes, the 'help' cursor is done on purpose since the component is meant to be explaining the main text. I thought that changing the cursor will make it more obvious that the extra text is an optional text.

I really like the idea of the 'help' cursor. However it is a bit confusing to show a question mark next to the cursor. Maybe you could make the change on the cursor itself, e.g. make its outer edge glow when hovering over the hover element? But this is more of a style thing, which we could always change it later.

**Comment by darrenlean** [comment]
The help cursor and event emitter have been removed

**Pull request merged**
