### PR TITLE
Hover Button

### PR DESCRIPTION
**Pull request by krammyt**
A button that highlights when the cursor hovers over it.

It has no props. It emits 3 types of events: When the mouse moves onto the button, when it moves off the button, and when the button is clicked.

P1

It has two methods: buttonClick and changeState, which are called when the button is clicked, and when the mouse moves on or off of the mouse, respectively. 

P2

The button has no computed properties, and has four data attributes: "hovering", "text", "on_off", and "depressed".

P3

### CODE REVIEW

**Comment by darrenlean** [comment]
Hey Mark,

Good button but perhaps you should stop calling it demo button, I almost could not find it! 
A few points here:
1. Is there any reason you choose to make a data (on-off) that stores hovering?
2. Have you consider including a way to disable the button?

Screenshot 2020-07-01 at 2 16 06 pm

**Comment by krammyt** [comment]
Hi both,
I've resolved the issue of the Hover button appearing in the wrong location.

Darren: I stored the on-off data as a way of implementing the background shading change, do you think I could do this more simply?

Could you explain what you mean what you mean by disable the button?

**Comment by darrenlean** [comment]
> Hi both,
> I've resolved the issue of the Hover button appearing in the wrong location.
> 
> Darren: I stored the on-off data as a way of implementing the background shading change, do you think I could do this more simply?
> 
> Could you explain what you mean what you mean by disable the button?

Hey Mark, 

The hovering shading can be implemented as a pure CSS property. For example, in ToggleBasic I have .toggleBasicLabel:hover{
_some properties that gets triggered when cursor is on toggleBasicLabel_
}

As for the depressed property, you should have a think about the functionality of the button -  Do you want it to be binary like ToggleBasic or just emitting neutral events upon clicking?

In ToggleBasic for example, I have this props that allows us to pass a Boolean that can disable the functionality of the toggle, i.e. the toggle becomes non-reactive, and turns the toggle grey to inform the user. This disable props can be useful in situations like when a vis is playing, we want to prevent the users from changing certain parameters.

**Comment by krammyt** [comment]
Following Darren's comments,
I've re-implemented the shading as a purely CSS property. Since the component is a button, I decided that having an on-off piece of data was pointless, provided I kept the event emitted when the button is clicked. Following this mindset, I took followed the direction Darren took and got rid of the button's "depressed" property.

I've also now added the option for the button to be disabled, as in the basic toggle.

**Comment by FreyaXH** [comment]
Nice work Mark, quick question on the disabling feature, what should I do to disable the button?

**Comment by OneOneFour** [comment]
Quick shout on this, @krammyt you are going to need to merge with upstream/dev before you are able to merge this PR, this may also involve you having to make a new PR, tho try to stick with this one if you can (the discussion is good 😄 )

**Comment by krammyt** [comment]
@FreyaXH just choose the diabled tickbox in prop, it should disable the button in the same way as in the basic toggle.

@OneOneFour Noted!

**Comment by darrenlean** [comment]
Hey Mark,

Is there any reason you choose to keep "hovering" in data and to emit the hovering events? What are the example situations where we want hovering events to trigger other events?

**Comment by krammyt** [comment]
Hi Darren,
good spot! I'll either get rid of the hovering data or remove the events being emitted, as having both is unnecessary. The idea I have in mind is that before clicking the button, it might be useful that a region relevant to the button being clicked might become highlighted (or something similar). 

It has been discussed that RK is coming up with a solution for the slots issue.

**Comment by krammyt** [comment]
@Puredbest it seems not. It's gone now!

**Pull request merged**
