### PR TITLE
Resolving issues #28

### PR DESCRIPTION
**Pull request by darrenlean**
After taking issue #28 into account, the size of the non-reactive LoadingSpinner can now be controlled with a prop "spinnerScaling"

Screenshot 2020-07-08 at 10 27 24 am
Screenshot 2020-07-08 at 10 27 24 am 1

### CODE REVIEW

**Comment by Puredbest** [comment]
Looks good, on a similar note I think it might be better to change the loading bar to use relative units instead of pixels.

**Comment by krammyt** [comment]
Hey Darren,
would it make sense to remove the option of having a spinner of zero size?

**Comment by darrenlean** [comment]
> Hey Darren,
> would it make sense to remove the option of having a spinner of zero size?

Hey Mark,

I have now made a default whereby zero size will turn into 0.5 scaling. 

This PR now also addresses the relative unit issue in #24 such that both LoadingSpinner and LoadingBar have relative unit and should work on various platforms.

**Comment by OneOneFour** [comment]
make sure to **Squash** before you merge

**Comment by OneOneFour** [comment]
image
^^ the button should look like this ^^

**Comment by OneOneFour** [comment]
> Hi Darren,
> I would disagree with using vh in this context, the reason being that for the case that the spinner would be used, it is likely to be used in the context of an absolutely sized element.

For example using the loader inside of say an element such as @Puredbest 's equation box or inside the button, elements like this will typically have the width set either using px or em but almost certainly **not** vh or vw.

**Comment by darrenlean** [comment]
> > Hi Darren,
> > I would disagree with using vh in this context, the reason being that for the case that the spinner would be used, it is likely to be used in the context of an absolutely sized element.
> 
> For example using the loader inside of say an element such as @Puredbest 's equation box or inside the button, elements like this will typically have the width set either using px or em but almost certainly **not** vh or vw.

What about when vis user open the vis on other platforms e.g. phone? Don't we want the loader to scale accordingly too?

**Comment by OneOneFour** [comment]
Yes but a better (and optimal) way to handle this would be using CSS media queries

**Comment by darrenlean** [comment]
> Yes but a better (and optimal) way to handle this would be using CSS media queries

I agree using CSS media queries is the best way forward but it requires more research, thoughts and the collaboration of design of the layout and the other components. Since our priority is to get the desktop website polished, I would leave this to a later stage when the layout team has done the desktop layout and is ready (and have the time to) dive into mobile site design. 

This PR will now only introduce the prop that scales the size of LoadingSpinner and hence aims to resolve issue #28. There is still a default setting for the null scaling case.

**Comment by OneOneFour** [comment]
Fair, I will raise it as an issue for the future

**Comment by OneOneFour** [comment]
Oh wait, you are using absolute px for now anyway fair nuff, I guess something we can still jot down as a change, do you know of any of components that are using vw/vh?

**Comment by darrenlean** [comment]
> Oh wait, you are using absolute px for now anyway fair nuff, I guess something we can still jot down as a change, do you know of any of components that are using vw/vh?

Yup, I have made a survey - those that use a mixture of absolute and relative units are LoadingBar and TitleBar; those that use pure relative units are Play_Button and EquationBox.

**Pull request merged**
